name: first workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Print Hello
        run: .scripts/helloworld.sh
        
      - name: Print bye
        run: echo "bye bye"
