name: first workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: ./helloworld.sh
      - name: Print bye
        run: echo "bye bye"
